version: '3'

services:
  todotests:
    build: ./todo-app/tests/
    environment:
      - FRONT_HOST=todofront
    networks:
      - app-network
    depends_on:
      - "todofront"
      - "todoback"

  todofront:
    build: ./todo-app/front-end/
    ports:
      - "3000:3001"
    environment:
      - REACT_APP_API_HOST=todoback
    networks:
      - app-network
    depends_on:
      - "todoback"

  todoback:
    build: ./todo-app/back-end/
    ports:
      - "3001:3001"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
